### ISSUE TITLE
✨ Feat: week10

### ISSUE THREAD

**Issue by jinnieusLab** [jinnieusLab/UMC6th#13]
## 📝 개요
- API 구현

## ✔️ To-Do
- [ ] 내가 작성한 리뷰 목록
- [ ] 특정 가게의 미션 목록
- [ ] 내가 진행중인 미션 목록
- [ ] 진행중인 미션 진행 완료로 바꾸기

## 👀 ETC
- 참고자료 등 기타 내용 작성
